language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test 

after success:
  - docker build -t aren1994/client ./client
  - docker build -t aren1994/nginx ./nginx
  - docker build -t aren1994/server ./server
  - docker build -t aren1994/worker ./worker
#Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push images to DockerHub
  - docker push aren1994/client 
  - docker push aren1994/nginx
  - docker push aren1994/server
  - docker push aren1994/worker

