language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t react-test -f ./client/dockerfile.dev ./client
script:
  - docker run -e CI=true react-test npm test 
after success:
  - docker build -t aren1994/client ./client
  - docker build -t aren1994/nginx ./nginx
  - docker build -t aren1994/server ./server
  - docker build -t aren1994/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aren1994/client 
  - docker push aren1994/nginx
  - docker push aren1994/server
  - docker push aren1994/worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-287403783854
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
