language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test 

after success:
  - docker build -t client ./client
  - docker build -t nginx ./nginx
  - docker build -t server ./server
  - docker build -t worker ./worker
#Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push images to DockerHub
  - docker push client 
  - docker push nginx
  - docker push server
  - docker push worker

